alias: Enable PID controller only when thermostat mode is heat or cool
description: ""
triggers:
  - trigger: state
    entity_id:
      - climate.upstairs
    to:
      - heat
      - cool
    id: climate_on
  - trigger: state
    entity_id:
      - climate.upstairs
    to:
      - "off"
    id: climate_off
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - climate_on
        sequence:
          - action: switch.turn_on
            metadata: {}
            target:
              entity_id: switch.damper_pid_auto_mode
            data: {}
      - conditions:
          - condition: trigger
            id:
              - climate_off
        sequence:
          - action: switch.turn_off
            metadata: {}
            target:
              entity_id: switch.damper_pid_auto_mode
            data: {}
mode: single
